language: node_js
node_js: "stable"

before_install:
  - stty cols 80

os: linux
dist: trusty

addons:
  firefox: latest
  chrome: stable
  apt:
    packages:
     - fluxbox

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3
  - fluxbox >/dev/null 2>&1 &
  - python -m SimpleHTTPServer &
  - sleep 2
